apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: agent-state
  namespace: match-scraper
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: linode-block-storage-retain
  resources:
    requests:
      storage: 1Gi
