apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: agent-state
  namespace: match-scraper
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 64Mi
